name: Release to Maven Central

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    secrets:
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true
      GPG_PASSPHRASE:
        required: true
      GPG_PRIVATE_KEY:
        required: true

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to Maven Central
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4 # Does also set up Maven and GPG
        with:
          distribution: 'temurin' # As good as any other, see: https://github.com/actions/setup-java#supported-distributions
          java-version: '17'
          server-id: 'central'
          server-username: ${{ secrets.MAVEN_USERNAME }}
          server-password: ${{ secrets.MAVEN_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Debug Maven Settings
        run: cat ~/.m2/settings.xml
      - name: Set version
        run: |
          VERSION=${{ inputs.tag_name }}
          VERSION=${VERSION#v}
          mvn versions:set -DnewVersion=$VERSION
          mvn versions:commit
      - name: Build & Deploy
        run: mvn -U -B clean deploy
